apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse-proxy
    database: ecommerce
    user: admin
    secureJsonData:
      password: admin123
    jsonData:
      defaultDatabase: ecommerce
      server: clickhouse-proxy
      port: 80
      protocol: http
